---
#### BeatDiabet.es landing page Ansible deployment playbook
#
# Overview: Playbook to bootstrap a new host for configuration management.
#           based on http://practicalops.com/my-first-5-minutes-on-a-server.html
# Applies to: production
# Description:
#    Ensures that a host is configured for management with Ansible.
#
###########

- hosts: newservers
  user: vagrant
  sudo: True

  tasks:

    - name: remove default nginx site
      action: file path=/etc/nginx/sites-enabled/default state=absent

    - name: write nginx.conf
      action: template src=templates/nginx/nginx.conf dest=/etc/nginx/nginx.conf

    - name: write nginx upstart script
      action: template src=templates/system/nginx.conf dest=/etc/init/nginx.conf

    - name: create supervisord config folder
      action: file dest=/etc/supervisor state=directory owner=root

    - name: create supervisord config
      action: template src=templates/supervisord.conf dest=/etc/supervisord.conf

    - name: create supervisord init script
      action: template src=templates/supervisord.sh dest=/etc/init.d/supervisord mode=0755

    - name: start supervisord service and have it run during system startup
      action: service name=supervisord state=started enabled=yes

    - name: create bdapp directory
      action: file dest=/srv/bdapp state=directory
