---
#### BeatDiabet.es landing page Ansible deployment playbook
#
# Overview: Playbook to bootstrap a new host for configuration management.
#           based on http://practicalops.com/my-first-5-minutes-on-a-server.html
# Applies to: production
# Description:
#    Ensures that a host is configured for management with Ansible.
#
###########

- hosts: newservers
  user: vagrant
  sudo: True

  tasks:

    - name: Remove sudo group rights
      action: lineinfile dest=/etc/sudoers regexp="^%sudo" state=absent

    - name: Add deploy user to sudoers
      action: lineinfile dest=/etc/sudoers regexp="deploy ALL" line="deploy ALL=(ALL) ALL" state=present

    - name: write sshd_config
      action: template src=templates/system/sshd_config  dest=/etc/ssh/sshd_config
      notify: Restart sshd

    - name: Adjust APT update intervals
      action: copy src=templates/system/apt_periodic dest=/etc/apt/apt.conf.d/10periodic

    - name: Make sure unattended-upgrades only installs from $ubuntu_release-security
      action: lineinfile dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent

  - name: Copy debconf selections so that Postfix can configure itself non-interactively
    copy: src=templates/system/postfix_selections  dest=/tmp/postfix_selections

  - name: Set up Postfix to relay mail
    action: command debconf-set-selections /tmp/postfix_selections

  - name: Make logwatch mail $logwatch_email daily
    action: lineinfile dest=/etc/cron.daily/00logwatch regexp="^/usr/sbin/logwatch" line="/usr/sbin/logwatch --output mail --mailto $logwatch_email --detail high" state=present create=yes

  - name: remove default nginx site
    action: file path=/etc/nginx/sites-enabled/default state=absent

  - name: write nginx.conf
    action: template src=templates/nginx.conf dest=/etc/nginx/nginx.conf

   - name: create supervisord config folder
    action: file dest=/etc/supervisor state=directory owner=root

  - name: create supervisord config
    action: template src=templates/supervisord.conf dest=/etc/supervisord.conf

  - name: create supervisord init script
    action: template src=templates/supervisord.sh dest=/etc/init.d/supervisord mode=0755

  - name: start supervisord service and have it run during system startup
    action: service name=supervisord state=started enabled=yes

  - name: create webapps directory
    action: file dest=/srv/webapps state=directory

  handlers:
  - name: Restart sshd
    action: service name=sshd state=restarted
